Added work section
kemar-art/My-Portfolio pull request #2
Opened 2021-12-02 19:16 UTC by kemar-art

The second page was added to my portfolio project.
Content
- HTML
- CSS

2021-12-02 21:06 UTC, rotimiazeez requested changes
# Hi @kemar-art 👋, 
## Good job so far!👏
### There are some issues that you still need to work on to go to the next project but you are almost there!😉
> Kindly complete the rest of the project as per the project requirement👍 so you can continue to the next project

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-02 21:06 UTC, rotimiazeez commented on index.html
> +      </div>
- [x] Good job using an `hx` tag here👍, kindly make sure you use `h2-h6` tag as you should have only one `h1` on your page so the `search engine` can find it easily 😉

2021-12-02 21:06 UTC, rotimiazeez commented on index.html
> +      </section>
- [ ] Kindly make sure your design matches the one on your preferred template✌
- Your design
![screenshot (47)](https://user-images.githubusercontent.com/44624138/144500292-9630a6e4-42ee-48c1-81df-14acadcf0fcd.png)
- Figma design
![screenshot (48)](https://user-images.githubusercontent.com/44624138/144500634-49d8e16e-7f00-474d-8f9c-dbb7e1d24127.png)

2021-12-02 21:06 UTC, rotimiazeez commented on index.html
> +      </section>
- [ ] Kindly complete the rest of the project as seen in the template and project requirement✔
- Add the remaining work cards
![screenshot (45)](https://user-images.githubusercontent.com/44624138/144502362-798078a4-157e-4db1-ab8f-57ba0adf66ab.png)
- Add the about page
 ![screenshot (46)](https://user-images.githubusercontent.com/44624138/144502065-28d2d73a-9d64-45df-b5d8-d728f2c59581.png)

2021-12-02 22:58 UTC, kemar-art commented on index.html
> +      </section>
This was done

2021-12-04 05:04 UTC, andersonlebon approved these changes
## Hi @kemar-art 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub flow :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your design looks good :+1: :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-04 05:04 UTC, andersonlebon commented on README.md
> +> I have now added the second page to my portfolio project, on this page my proficiency will desplay. But still no functionality added to the page as yet.
## [OPTIONAL] 
- [ ] To make your README file more professional I would suggest adding a screenshot of the project in it.

2021-12-04 05:13 UTC, merged